-- HRMS Letter Module: production-safe schema addition
--
-- UP MIGRATION
-- Creates only the new Letter Module metadata tables. It does not alter,
-- delete, or migrate any existing HRMS data or tables.

CREATE TABLE IF NOT EXISTS public.letter_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letter_type VARCHAR(32) NOT NULL,
    -- An offer can be prepared before its candidate has a HRMS employee record.
    -- Experience/relieving requests validate this value in the API.
    employee_id INTEGER,
    reference_number VARCHAR(100),
    branch VARCHAR(100),
    last_working_date DATE,
    relieving_date DATE,
    issue_date DATE,
    job_description TEXT,
    editable_content TEXT,
    recipient_email VARCHAR(255),
    -- Only the editable values are retained. Rendered HTML and PDFs are
    -- generated on demand and are deliberately never stored on disk or in DB.
    document_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_by INTEGER NOT NULL,
    updated_by INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT letter_requests_letter_type_check
        CHECK (letter_type IN ('OFFER', 'EXPERIENCE_RELIEVING')),
    CONSTRAINT letter_requests_letter_type_key UNIQUE (letter_type),
    CONSTRAINT letter_requests_employee_id_fkey
        FOREIGN KEY (employee_id) REFERENCES public.users(id) ON DELETE RESTRICT,
    CONSTRAINT letter_requests_created_by_fkey
        FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE RESTRICT,
    CONSTRAINT letter_requests_updated_by_fkey
        FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_letter_requests_employee_id
    ON public.letter_requests (employee_id);

CREATE INDEX IF NOT EXISTS idx_letter_requests_status
    ON public.letter_requests (status);

CREATE TABLE IF NOT EXISTS public.letter_email_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letter_request_id INTEGER NOT NULL,
    employee_email VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL,
    error_message TEXT,
    sent_by INTEGER,
    sent_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT letter_email_logs_letter_request_id_fkey
        FOREIGN KEY (letter_request_id) REFERENCES public.letter_requests(id) ON DELETE RESTRICT,
    CONSTRAINT letter_email_logs_sent_by_fkey
        FOREIGN KEY (sent_by) REFERENCES public.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_letter_email_logs_request_sent_at
    ON public.letter_email_logs (letter_request_id, sent_at DESC);

CREATE INDEX IF NOT EXISTS idx_letter_email_logs_sent_by
    ON public.letter_email_logs (sent_by);

-- Safe when this migration is re-run after an earlier development version.
ALTER TABLE public.letter_requests
    ADD COLUMN IF NOT EXISTS document_data JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.letter_requests
    ALTER COLUMN employee_id DROP NOT NULL;

-- DOWN MIGRATION
-- Run only as an explicitly approved rollback. It removes only the two tables
-- created by this migration and leaves every existing HRMS table untouched.
--
-- DROP TABLE IF EXISTS public.letter_email_logs;
-- DROP TABLE IF EXISTS public.letter_requests;
